
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pre-commit
      - name: Lint
        run: pre-commit run --all-files || true
      - name: Train model (quick)
        run: python ml/train_tabular.py
      - name: Build RAG index (ok if empty)
        run: python rag/build_index.py || true
      - name: Run tests
        run: pytest
