name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUNBUFFERED: '1'
      PYTHONUTF8: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt
          pip install -e .
      - name: Smoke import
        run: python -c "import ts_guard; print('ts_guard:', ts_guard.__file__)"
      - name: Tests
        run: python -m pytest -vv -ra --maxfail=1
